fix: solving image component
ecomclub/storefront-ui pull request #2
Opened 2019-08-25 03:53 UTC by matheusgnreis

Check if it’s working

2019-08-25 04:47 UTC, leomp12 requested changes

2019-08-25 04:47 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.html
> +  <picture ref="picture" loading="lazy" class="sf-image__img lozad" v-else>
melhor verificar o array images aqui, e depois ainda teria um v-else com o placeholder...

```suggestion
  <picture ref="picture" loading="lazy" class="sf-image__img" v-else-if="images && images.length">
```

2019-08-25 04:47 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.html
> +    <source ref="pictureSmall" media="(max-width: 767px)">
por quê não jogar o srcset aqui de uma vez?
```suggestion
    <source srcset="pictures[0].normal.url" media="(max-width: 767px)">
```

2019-08-25 04:47 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.html
> +  <img ref="img" loading="lazy" class="sf-image__img lozad" v-if="src" />
não precisa mais do loadind=lazy porque vamos suar lozad, e a classe lozad também não é necessária porque você está criando o observer pela classe sf-image__img, certo?

```suggestion
  <img :data-src="src" class="sf-image__img" v-if="src" />
```

2019-08-25 04:47 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.js
> +      this.$refs.img.setAttribute("src", this.src);
acho que é melhor setar o src no template como sugeri acima, e desta forma você pode remover estes setAttribute no mounted

2019-08-25 16:09 UTC, matheusgnreis commented on packages/vue/src/components/molecules/SfImage/SfImage.js
> +      this.$refs.img.setAttribute("src", this.src);
Nesse caso, eu edito e envio novamente, ou já foi modificado? Porquê nesse não está me mostrando a opção de dar commit na alteração.

2019-08-25 19:58 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.js
> +      this.$refs.img.setAttribute("src", this.src);
é só você dar push no mesmo branch image que vai atualizar no pr, é isto mesmo que perguntou?

2019-08-25 19:59 UTC, leomp12 commented on packages/vue/src/components/molecules/SfImage/SfImage.js
> +      this.$refs.img.setAttribute("src", this.src);
este não está te mostrando a opção de commitar porque eu não sugeri uma alteração no código porque tem que alterar em várias linhas, então eu só comentei..

2019-08-27 00:39 UTC, leomp12 commented
atualizamos este componente...

2019-08-27 00:39 UTC, closed without merging